//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopWPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string About { get; set; }
        public int Year { get; set; }
        public int Pages { get; set; }
        public int PublisherId { get; set; }
        public int GenreId { get; set; }
        public int AuthorId { get; set; }
        public double Price { get; set; }
    
        public virtual Publisher Publisher { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Author Author { get; set; }
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
